const actionTypes = {
  GET_EMPLOYEE_REQUEST: "GET_EMPLOYEE_REQUEST",
  GET_EMPLOYEE_RECEIVED: "GET_EMPLOYEE_RECEIVED",
  EDIT_EMPLOYEE_REQUEST: "EDIT_EMPLOYEE_REQUEST",
  EDIT_EMPLOYEE_RECIVED: "EDIT_EMPLOYEE_RECIVED",
};

export default actionTypes;
